name: Build and deploy to crates.io
on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/publish.yml'
    - 'Cargo.toml'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
    - run: cargo publish
